version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9900:9900"
    volumes:
      - ./pb_data:/app
    restart: unless-stopped
    environment:
      - ADMIN_EMAIL=admin@pocketbase-starter.com
      - ADMIN_PASSWORD=0123456789